name       : python-injector
version    : 0.18.4
release    : 1
source     :
    - https://github.com/alecthomas/injector/archive/refs/tags/0.18.4.tar.gz : 9f00f16bb667142a076073af0df2c30013b1fc4c032c49029ad2f9bcba88d3b9
license    : BSD-3-Clause
component  : programming.python
summary    : Python dependency injection framework
description: |
    Python dependency injection framework
builddeps  :
   - pkgconfig(python3)
   - python-typing-extensions
rundeps    :
   - python3
   - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
