name       : python-injector
version    : 0.20.1
release    : 5
source     :
    - https://github.com/alecthomas/injector/archive/refs/tags/0.20.1.tar.gz : 4111f322485980a1191b5a886088ad2ae0c41837fe0ad05d961fe4ecdb673519
homepage   : https://github.com/twisted/incremental
license    : BSD-3-Clause
component  : programming.python
summary    : Python dependency injection framework
description: |
    Python dependency injection framework
builddeps  :
    - pkgconfig(python3)
    - python-typing-extensions
rundeps    :
    - python3
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
